import { Modal } from "@mantine/core";
import useAppStore from "~/lib/stores/appStore";
import { FilePickerContent } from "../pages/files/components/FilePickerContent";
import type { FileData, FileTypeFilter } from "~/lib/stores/filesFoldersStore";

interface FilePickerModalProps {
  opened: boolean;
  onClose: () => void;
  onSelect: (fileUrl: string, file?: FileData) => void;
  /** When set, shows paste-URL next to upload in the modal and calls this then closes the modal. */
  onPasteUrl?: (url: string) => void;
  title?: string;
  allowedTypes?: FileTypeFilter; // Filter by file type, default is "all"
  /** When set, only list files generated by this gen model (`user_files.gen_model_id`). */
  genModelId?: string;
}

export function FilePickerModal({
  opened,
  onClose,
  onSelect,
  onPasteUrl,
  title = "Select File",
  allowedTypes = "all",
  genModelId,
}: FilePickerModalProps) {
  const { isMobile } = useAppStore();

  const handleFileSelect = (file: FileData) => {
    onSelect(file.file_path, file);
    onClose();
  };

  const handleUploadComplete = async () => {
    // Refresh will be handled by FilePickerContent
  };

  const handlePasteUrl = (url: string) => {
    onPasteUrl?.(url);
    onClose();
  };

  return (
    <Modal
      opened={opened}
      onClose={onClose}
      title={title}
      size="xl"
      fullScreen={isMobile}
      centered={!isMobile}
      overlayProps={{ backgroundOpacity: 0.5, blur: 4 }}
    >
      <FilePickerContent
        onFileSelect={handleFileSelect}
        allowedTypes={allowedTypes}
        genModelId={genModelId}
        showUpload={true}
        onUploadComplete={handleUploadComplete}
        onPasteUrl={onPasteUrl ? handlePasteUrl : undefined}
      />
    </Modal>
  );
}
