export const GENDER_OPTIONS = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "neutral", label: "Neutral" },
];

export const LANGUAGE_OPTIONS = [
  { value: "af", label: "Afrikaans (af)" },
  { value: "ar", label: "Arabic (ar)" },
  { value: "hy", label: "Armenian (hy)" },
  { value: "as", label: "Assamese (as)" },
  { value: "az", label: "Azerbaijani (az)" },
  { value: "be", label: "Belarusian (be)" },
  { value: "bn", label: "Bengali (bn)" },
  { value: "bs", label: "Bosnian (bs)" },
  { value: "bg", label: "Bulgarian (bg)" },
  { value: "ca", label: "Catalan (ca)" },
  { value: "ceb", label: "Cebuano (ceb)" },
  { value: "ny", label: "Chichewa (ny)" },
  { value: "hr", label: "Croatian (hr)" },
  { value: "cs", label: "Czech (cs)" },
  { value: "da", label: "Danish (da)" },
  { value: "nl", label: "Dutch (nl)" },
  { value: "en", label: "English (en)" },
  { value: "et", label: "Estonian (et)" },
  { value: "fil", label: "Filipino (fil)" },
  { value: "fi", label: "Finnish (fi)" },
  { value: "fr", label: "French (fr)" },
  { value: "gl", label: "Galician (gl)" },
  { value: "ka", label: "Georgian (ka)" },
  { value: "de", label: "German (de)" },
  { value: "el", label: "Greek (el)" },
  { value: "gu", label: "Gujarati (gu)" },
  { value: "ha", label: "Hausa (ha)" },
  { value: "he", label: "Hebrew (he)" },
  { value: "hi", label: "Hindi (hi)" },
  { value: "hu", label: "Hungarian (hu)" },
  { value: "is", label: "Icelandic (is)" },
  { value: "id", label: "Indonesian (id)" },
  { value: "ga", label: "Irish (ga)" },
  { value: "it", label: "Italian (it)" },
  { value: "ja", label: "Japanese (ja)" },
  { value: "jv", label: "Javanese (jv)" },
  { value: "kn", label: "Kannada (kn)" },
  { value: "kk", label: "Kazakh (kk)" },
  { value: "ky", label: "Kirghiz (ky)" },
  { value: "ko", label: "Korean (ko)" },
  { value: "lv", label: "Latvian (lv)" },
  { value: "ln", label: "Lingala (ln)" },
  { value: "lt", label: "Lithuanian (lt)" },
  { value: "lb", label: "Luxembourgish (lb)" },
  { value: "mk", label: "Macedonian (mk)" },
  { value: "ms", label: "Malay (ms)" },
  { value: "ml", label: "Malayalam (ml)" },
  { value: "zh", label: "Mandarin Chinese (zh)" },
  { value: "mr", label: "Marathi (mr)" },
  { value: "ne", label: "Nepali (ne)" },
  { value: "no", label: "Norwegian (no)" },
  { value: "ps", label: "Pashto (ps)" },
  { value: "fa", label: "Persian (fa)" },
  { value: "pl", label: "Polish (pl)" },
  { value: "pt", label: "Portuguese (pt)" },
  { value: "pa", label: "Punjabi (pa)" },
  { value: "ro", label: "Romanian (ro)" },
  { value: "ru", label: "Russian (ru)" },
  { value: "sr", label: "Serbian (sr)" },
  { value: "sd", label: "Sindhi (sd)" },
  { value: "sk", label: "Slovak (sk)" },
  { value: "sl", label: "Slovenian (sl)" },
  { value: "so", label: "Somali (so)" },
  { value: "es", label: "Spanish (es)" },
  { value: "sw", label: "Swahili (sw)" },
  { value: "sv", label: "Swedish (sv)" },
  { value: "ta", label: "Tamil (ta)" },
  { value: "te", label: "Telugu (te)" },
  { value: "th", label: "Thai (th)" },
  { value: "tr", label: "Turkish (tr)" },
  { value: "uk", label: "Ukrainian (uk)" },
  { value: "ur", label: "Urdu (ur)" },
  { value: "vi", label: "Vietnamese (vi)" },
  { value: "cy", label: "Welsh (cy)" },
];

export const ACCENT_OPTIONS = [
  { value: "standard", label: "Standard" },
  { value: "american", label: "American" },
  { value: "british", label: "British" },
  { value: "australian", label: "Australian" },
  { value: "canadian", label: "Canadian" },
  { value: "indian", label: "Indian" },
  { value: "irish", label: "Irish" },
  { value: "scottish", label: "Scottish" },
  { value: "south african", label: "South African" },
  { value: "new zealand", label: "New Zealand" },
  { value: "west indies", label: "West Indies" },
  { value: "american-southern", label: "American-Southern" },
  { value: "american-new york", label: "American-New York" },
  { value: "american-midwest", label: "American-Midwest" },
  { value: "british-london (cockney or posh)", label: "British-London (Cockney or Posh)" },
  { value: "spanish-castilian", label: "Spanish-Castilian" },
  { value: "spanish-latin american", label: "Spanish-Latin American" },
  { value: "portuguese-brazilian", label: "Portuguese-Brazilian" },
];

export const CATEGORY_OPTIONS = [
  { value: "professional", label: "professional" },
  { value: "famous", label: "famous" },
  { value: "high_quality", label: "high_quality" },
];
