/** ElevenLabs voice label accents (display labels sent as `labels.accent`). */
export const VOICE_ACCENT_OPTIONS = [
  "American",
  "Australian",
  "British",
  "Canadian",
  "Indian",
  "Irish",
  "Jamaican",
  "New Zealand",
  "Nigerian",
  "Scottish",
  "South African",
  "African American",
  "Singaporean",
  "US - Boston",
  "US - Chicago",
  "US - New York",
  "US - Southern",
  "US - Midwest",
  "US - Northeast",
  "Cockney",
  "Geordie",
  "Received Pronunciation",
  "Scouse",
  "Welsh",
  "Yorkshire",
  "Arabic",
  "Bulgarian",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Filipino",
  "Finnish",
  "French",
  "German",
  "Greek",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malay",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Slovak",
  "Spanish",
  "Swedish",
  "Tamil",
  "Turkish",
  "Ukrainian",
] as const;

export const voiceAccentSelectData = VOICE_ACCENT_OPTIONS.map((value) => ({
  value,
  label: value,
}));
